### ISSUE TITLE
[BUG] Invalid version string on rr get-binary

### ISSUE THREAD

**Issue by nil-nil** [spiral/roadrunner-cli#14]
@rustatian 
I'm getting an error when trying to do `rr get-binary`.
The version string referenced is the latest pre-release in the repo.

I tried this code:

```
/var/www/vendor/bin/rr get-binary
```

I expected to see this happen: a normal download of the binary

Instead, this happened: 
```
spiral/roadrunner#25 1.324 
spiral/roadrunner#25 1.324  Environment:
spiral/roadrunner#25 1.324    - Version:          2.*
spiral/roadrunner#25 1.326    - Stability:        stable
spiral/roadrunner#25 1.329    - Operating System: linux
spiral/roadrunner#25 1.329    - Architecture:     amd64
spiral/roadrunner#25 1.329 
spiral/roadrunner#25 1.993 
spiral/roadrunner#25 2.017 In VersionParser.php line 185:
spiral/roadrunner#25 2.018                                                              
spiral/roadrunner#25 2.018   Invalid version string "Plugins separate repo experiment"  
spiral/roadrunner#25 2.018                                                              
spiral/roadrunner#25 2.018 
spiral/roadrunner#25 2.018 get-binary [-o|--os [OS]] [-a|--arch [ARCH]] [-f|--filter [FILTER]] [-l|--location [LOCATION]] [-s|--stability [STABILITY]]
spiral/roadrunner#25 2.018 
```

The version of RR used: 2.*
  
My `.rr.yaml` configuration is: can supply if needed

**Comment by SerafimArts** [comment]
@nil-nil please upgrade to `spiral/roadrunner-cli: 2.0.8`

**Comment by nil-nil** [comment]
Thanks @SerafimArts that seems to fix it.
I'm using RoadRunner in Docker and worked around the issue by doing a multi-stage build and copying /usr/bin/rr from the official spiralscout/roadrunner:latest image.
Is it safe to do make that change permanent, instead of running `rr get-binary` in my Dockerfile?
Do I need to be careful that the RoadRunner version of the binary exactly matches the composer package version?

**Comment by SerafimArts** [comment]
> Do I need to be careful that the RoadRunner version of the binary exactly matches the composer package version?

Nope
