### ISSUE TITLE
[BUG?] Use the `roadrunner-binary` repository as the versions source for the CLI

### ISSUE THREAD

**Issue by rustatian** [spiral/roadrunner-cli#17]
We should not use `roadrunner` repo as the source of the versions for the PHP, please, use https://github.com/spiral/roadrunner-binary repository only.

**Comment by SerafimArts** [comment]
https://github.com/spiral/roadrunner-binary repository does not contain binaries for versions below 2.0 https://github.com/spiral/roadrunner-binary/tags?after=v2.0.0

This repository cannot be used to download PP 1.9.x and below.
