### ISSUE TITLE
get-binary failed to download in MacOS

### ISSUE THREAD

**Issue by Yurunsoft** [spiral/roadrunner-cli#19]
It works normally under windows and Linux

I try to run on the MacOS of GitHub action

`vendor/bin/rr get-binary`

```
 Environment:
   - Version:          2.*
   - Stability:        stable
   - Operating System: darwin
   - Architecture:     amd64


In CommonResponseTrait.php line 181:
                                                                               
  HTTP/2 403  returned for "https://api.github.com/repos/spiral/roadrunner/re  
  leases?page=1".                                                              
                                                                               

get-binary [-o|--os [OS]] [-a|--arch [ARCH]] [-f|--filter [FILTER]] [-l|--location [LOCATION]] [-s|--stability [STABILITY]]

Error: Process completed with exit code 255.
```

**Comment by alexander-schranz** [comment]
The error which seems to happen here is a Rate Limit error. If I open `https://api.github.com/repos/spiral/roadrunner/releases?page=1`
  
The response is:

```json
{
    "message": "API rate limit exceeded for 84.115.214.108. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
     "documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"
}
```

Maybe this ratelimit can be avoided by reusing the github authentication key from composer. Maybe here the composer core devs can be asked what the best way would be to get the authentication key which is stored in most cases under `~/.composer/auth.json` to avoid this rate limit.

**Comment by SerafimArts** [comment]
You can add env variable `GITHUB_TOKEN` with token https://github.com/spiral/roadrunner-cli/blob/master/src/Command.php#L39-L45

**Comment by Yurunsoft** [comment]
Thanks!
