### ISSUE TITLE
Check `ReleasesCollection::sortByVersion`

### ISSUE THREAD

**Issue by alexpts** [spiral/roadrunner-cli#2]
I try install latest rr version:
`./vendor/bin/rr get-binary`

Actual: `beta25`
Expected: `RC3` for linux, `RC2` for macos.

Discussion:
https://discord.com/channels/538114875570913290/696388921973801012/811690657214496778

**Comment by SerafimArts** [comment]
This bug occurred on the old version. In the current version, this problem has been fixed, but these fixes have not yet been released.

**Comment by SerafimArts** [comment]
@alexpts Try to reproduce the problem now. Versioning should be fixed:
![image](https://user-images.githubusercontent.com/2461257/108348788-46939200-71f3-11eb-81e7-724dc33de625.png)

**Comment by alexpts** [comment]
@SerafimArts  Fixed on `dev-master`.
