### ISSUE TITLE
Error when using get-binary due to name of latest roadrunner release

### ISSUE THREAD

**Issue by Jefemy** [spiral/roadrunner-cli#20]
The latest roadrunner version includes the word `Release` in front of the version, seen here https://github.com/spiral/roadrunner-binary/releases

This breaks the binary downloading process as it is no longer a valid version erroring with
```
In VersionParser.php line 185:
                                                  
  Invalid version string "Release v2.5.0-beta.1"  
  ```
Error thrown here https://github.com/composer/semver/blob/main/src/VersionParser.php#L185
Caused by https://github.com/spiral/roadrunner-cli/blob/master/src/Repository/Release.php#L79

Version name either must be skipped or have its error caught

**Comment by SerafimArts** [comment]
@Jefemy Hi! Try updating your version of the `roadrunner-cli` tool.
