### ISSUE TITLE
[BUG] Get-binary cannot handle debian packages.

### ISSUE THREAD

**Issue by Zylius** [spiral/roadrunner-cli#31]
Hello,

Since the 2.10 release includes a debian package, the get-binary command throws me this:

``` Can not open the archive "roadrunner-2.10.0-linux-amd64.deb":```
Easily recreated by getting the 2.10 version.

There's of course a way around this :D just reporting the bug.

**Comment by butschster** [comment]
Hi, @Zylius 
Thank you for report!

**Comment by inmanturbo** [comment]
> Hello,
> 
> Since the 2.10 release includes a debian package, the get-binary command throws me this:
> 
> ` Can not open the archive "roadrunner-2.10.0-linux-amd64.deb":` Easily recreated by getting the 2.10 version.
> 
> There's of course a way around this :D just reporting the bug.

Care to share? :pleading_face:  is there a better way around this than downgrading?

**Comment by butschster** [comment]
Done!

**Comment by Zylius** [comment]
> > Hello,
> > Since the 2.10 release includes a debian package, the get-binary command throws me this:
> > ` Can not open the archive "roadrunner-2.10.0-linux-amd64.deb":` Easily recreated by getting the 2.10 version.
> > There's of course a way around this :D just reporting the bug.
> 
> Care to share? pleading_face is there a better way around this than downgrading?

For the next time if you run into an issue the rr-cli, I just use

```
wget -c https://github.com/roadrunner-server/roadrunner/releases/download/v2.10.0/roadrunner-2.10.0-linux-amd64.tar.gz -O - | tar -xz -C /tmp/
cp /tmp/roadrunner-2.10.0-linux-amd64/rr /home/docker/.bin
```

Or something like this, you can also use the debian package. Urls are in the release page ;)
