### ISSUE TITLE
Change repository config host

### ISSUE THREAD

**Issue by kabunx** [spiral/roadrunner-cli#6]
```sh

RoadRunner (2.0.4) has been installed into /Users/user/Laravel/study/rr

In ErrorChunk.php line 65:
                                                                               
  Couldn't connect to server for "https://raw.githubusercontent.com/spiral/ro  
  adrunner-binary/v2.0.4/.rr.yaml".                                            
                                                                               

In CurlResponse.php line 317:
                                                                               
  Couldn't connect to server for "https://raw.githubusercontent.com/spiral/ro  
  adrunner-binary/v2.0.4/.rr.yaml".                                            
                                                                               

```

**Comment by 48d90782** [comment]
Hello @z-golly . Could you please add the description to your issue? It's not clear, why are you proposing to change the repository host.

**Comment by 48d90782** [comment]
The configuration (`.rr-yaml`) here is the SAMPLE configuration which is NOT supposed to be used. It might be deleted/moved/renamed at any time w/o notification.

**Comment by SerafimArts** [comment]
@z-golly i think whis is your temporary internet error. This file is present: https://raw.githubusercontent.com/spiral/roadrunner-binary/v2.0.4/.rr.yaml

**Comment by z-golly** [comment]
@48d90782 I think there are a lot of Chinese developers, we cannot access this resource without a VPN

**Comment by SerafimArts** [comment]
@z-golly what solutions to the problem do you propose?

**Comment by rustatian** [comment]
Closed due to inactivity. @kabunx We provide official binaries and configuration via GitHub.
