### ISSUE TITLE
get-binary cli command not compatible with symfony 4.4

### ISSUE THREAD

**Issue by drefixs** [spiral/roadrunner-cli#8]
hello :)

When i try to run 

```
vendor/bin/rr get-binary --location ./bin
```
i got the next error
```
Fatal error: Uncaught Error: Undefined class constant 'SUCCESS' in 
/vendor/spiral/roadrunner-cli/src/GetBinaryCommand.php:147
```

I have symfony 4.4 but the public SUCCESS constant appeared in version 5.1 in the base symfony command class.

**Comment by SerafimArts** [comment]
Yes, it seems the functionality has not been properly tested on the lowest version of the symfony.

**Comment by SerafimArts** [comment]
Done https://github.com/spiral/roadrunner-cli/commit/7550cba71af95a7eb05cae25debb5bc8d3a6a8dc
